const teams = [
  {
    id: 1,
    abbreviation: 'ATL',
    city: 'Atlanta',
    conference: 'East',
    division: 'Southeast',
    full_name: 'Atlanta Hawks',
    name: 'Hawks',
    location: [33.7566252, -84.3954465],
  },
  {
    id: 2,
    abbreviation: 'BOS',
    city: 'Boston',
    conference: 'East',
    division: 'Atlantic',
    full_name: 'Boston Celtics',
    name: 'Celtics',
    location: [42.3663136, -71.0644146],
  },
  {
    id: 3,
    abbreviation: 'BKN',
    city: 'Brooklyn',
    conference: 'East',
    division: 'Atlantic',
    full_name: 'Brooklyn Nets',
    name: 'Nets',
    location: [40.6826539, -73.9776019],
  },
  {
    id: 4,
    abbreviation: 'CHA',
    city: 'Charlotte',
    conference: 'East',
    division: 'Southeast',
    full_name: 'Charlotte Hornets',
    name: 'Hornets',
    location: [35.2251426, -80.8392351],
  },
  {
    id: 5,
    abbreviation: 'CHI',
    city: 'Chicago',
    conference: 'East',
    division: 'Central',
    full_name: 'Chicago Bulls',
    name: 'Bulls',
    location: [41.8806948, -87.6763646],
  },
  {
    id: 6,
    abbreviation: 'CLE',
    city: 'Cleveland',
    conference: 'East',
    division: 'Central',
    full_name: 'Cleveland Cavaliers',
    name: 'Cavaliers',
    location: [41.4964837, -81.6904016],
  },
  {
    id: 7,
    abbreviation: 'DAL',
    city: 'Dallas',
    conference: 'West',
    division: 'Southwest',
    full_name: 'Dallas Mavericks',
    name: 'Mavericks',
    location: [32.7905109, -96.8125436],
  },
  {
    id: 8,
    abbreviation: 'DEN',
    city: 'Denver',
    conference: 'West',
    division: 'Northwest',
    full_name: 'Denver Nuggets',
    name: 'Nuggets',
    location: [39.7486641, -105.0098987],
  },
  {
    id: 9,
    abbreviation: 'DET',
    city: 'Detroit',
    conference: 'East',
    division: 'Central',
    full_name: 'Detroit Pistons',
    name: 'Pistons',
    location: [42.3360146, -83.0949474],
  },
  {
    id: 10,
    abbreviation: 'GSW',
    city: 'Golden State',
    conference: 'West',
    division: 'Pacific',
    full_name: 'Golden State Warriors',
    name: 'Warriors',
    location: [37.7503066, -122.2051494],
  },
  {
    id: 11,
    abbreviation: 'HOU',
    city: 'Houston',
    conference: 'West',
    division: 'Southwest',
    full_name: 'Houston Rockets',
    name: 'Rockets',
    location: [29.750765, -95.3642892],
  },
  {
    id: 12,
    abbreviation: 'IND',
    city: 'Indiana',
    conference: 'East',
    division: 'Central',
    full_name: 'Indiana Pacers',
    name: 'Pacers',
    location: [39.7638908, -86.1576474],
  },
  {
    id: 13,
    abbreviation: 'LAC',
    city: 'LA',
    conference: 'West',
    division: 'Pacific',
    full_name: 'LA Clippers',
    name: 'Clippers',
    location: [34.0430175,-118.2672541],
  },
  {
    id: 14,
    abbreviation: 'LAL',
    city: 'Los Angeles',
    conference: 'West',
    division: 'Pacific',
    full_name: 'Los Angeles Lakers',
    name: 'Lakers',
    location: [34.0430219, -118.2694428],
  },
  {
    id: 15,
    abbreviation: 'MEM',
    city: 'Memphis',
    conference: 'West',
    division: 'Southwest',
    full_name: 'Memphis Grizzlies',
    name: 'Grizzlies',
    location: [35.1382087, -90.0526622],
  },
  {
    id: 16,
    abbreviation: 'MIA',
    city: 'Miami',
    conference: 'East',
    division: 'Southeast',
    full_name: 'Miami Heat',
    name: 'Heat',
    location: [25.7814062, -80.1891577],
  },
  {
    id: 17,
    abbreviation: 'MIL',
    city: 'Milwaukee',
    conference: 'East',
    division: 'Central',
    full_name: 'Milwaukee Bucks',
    name: 'Bucks',
    location: [43.0433658, -87.9191557],
  },
  {
    id: 18,
    abbreviation: 'MIN',
    city: 'Minnesota',
    conference: 'West',
    division: 'Northwest',
    full_name: 'Minnesota Timberwolves',
    name: 'Timberwolves',
    location: [44.9795318, -93.2781777],
  },
  {
    id: 19,
    abbreviation: 'NOP',
    city: 'New Orleans',
    conference: 'West',
    division: 'Southwest',
    full_name: 'New Orleans Pelicans',
    name: 'Pelicans',
    location: [29.9490397, -90.0842455],
  },
  {
    id: 20,
    abbreviation: 'NYK',
    city: 'New York',
    conference: 'East',
    division: 'Atlantic',
    full_name: 'New York Knicks',
    name: 'Knicks',
    location: [40.7505045, -73.9934387],
  },
  {
    id: 21,
    abbreviation: 'OKC',
    city: 'Oklahoma City',
    conference: 'West',
    division: 'Northwest',
    full_name: 'Oklahoma City Thunder',
    name: 'Thunder',
    location: [35.4634218, -97.5173063],
  },
  {
    id: 22,
    abbreviation: 'ORL',
    city: 'Orlando',
    conference: 'East',
    division: 'Southeast',
    full_name: 'Orlando Magic',
    name: 'Magic',
    location: [28.5392261, -81.3860422],
  },
  {
    id: 23,
    abbreviation: 'PHI',
    city: 'Philadelphia',
    conference: 'East',
    division: 'Atlantic',
    full_name: 'Philadelphia 76ers',
    name: '76ers',
    location: [39.9012056, -75.1741682],
  },
  {
    id: 24,
    abbreviation: 'PHX',
    city: 'Phoenix',
    conference: 'West',
    division: 'Pacific',
    full_name: 'Phoenix Suns',
    name: 'Suns',
    location: [33.4457414, -112.0733893],
  },
  {
    id: 25,
    abbreviation: 'POR',
    city: 'Portland',
    conference: 'West',
    division: 'Northwest',
    full_name: 'Portland Trail Blazers',
    name: 'Trail Blazers',
    location: [45.5315688, -122.669031],
  },
  {
    id: 26,
    abbreviation: 'SAC',
    city: 'Sacramento',
    conference: 'West',
    division: 'Pacific',
    full_name: 'Sacramento Kings',
    name: 'Kings',
    location: [33.753746, -84.386330],
  },
  {
    id: 27,
    abbreviation: 'SAS',
    city: 'San Antonio',
    conference: 'West',
    division: 'Southwest',
    full_name: 'San Antonio Spurs',
    name: 'Spurs',
    location: [29.4268607, -98.4383745],
  },
  {
    id: 28,
    abbreviation: 'TOR',
    city: 'Toronto',
    conference: 'East',
    division: 'Atlantic',
    full_name: 'Toronto Raptors',
    name: 'Raptors',
    location: [43.64347, -79.3812876],
  },
  {
    id: 29,
    abbreviation: 'UTA',
    city: 'Utah',
    conference: 'West',
    division: 'Northwest',
    full_name: 'Utah Jazz',
    name: 'Jazz',
    location: [40.7682721, -111.9032761],
  },
  {
    id: 30,
    abbreviation: 'WAS',
    city: 'Washington',
    conference: 'East',
    division: 'Southeast',
    full_name: 'Washington Wizards',
    name: 'Wizards',
    location: [38.8980623, -77.0230686],
  },
];

exports.teams = teams;
